# Generated by Django 5.2.7 on 2025-10-15 17:53

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='problem',
            name='solved_by',
            field=models.ManyToManyField(blank=True, related_name='solved_problems', to=settings.AUTH_USER_MODEL),
        ),
    ]
