# Generated by Django 5.2.7 on 2025-10-29 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='current_streak',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_daily_challenge_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
