# Generated by Django 5.2.7 on 2025-11-07 06:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_problem_category_speedrunattempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MapCheckpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkpoint_number', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('emoji', models.CharField(default='🏝️', max_length=10)),
                ('difficulty_level', models.IntegerField(choices=[(1, 'Beginner Bay'), (2, "Sailor's Strait"), (3, 'Corsair Cove'), (4, "Captain's Channel"), (5, "Legend's Lagoon")], default=1)),
                ('position_x', models.IntegerField(default=0)),
                ('position_y', models.IntegerField(default=0)),
                ('problems_to_unlock', models.IntegerField(default=3)),
                ('points_reward', models.IntegerField(default=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['checkpoint_number'],
            },
        ),
        migrations.CreateModel(
            name='UserProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problems_solved_at_current', models.IntegerField(default=0)),
                ('total_checkpoints_completed', models.IntegerField(default=0)),
                ('total_map_problems_solved', models.IntegerField(default=0)),
                ('journey_started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('current_checkpoint', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_users', to='app.mapcheckpoint')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='map_progress', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Map Progress',
                'verbose_name_plural': 'User Map Progresses',
            },
        ),
    ]
